name: run-tests

on: [push, pull_request]

jobs:
    fix-code-style:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Fix style
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --config=.php_cs --allow-risky=yes

            -   name: Extract branch name
                shell: bash
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
                id: extract_branch

            -   name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v2.3.0
                with:
                    commit_message: fix code style
                    branch: ${{ steps.extract_branch.outputs.branch }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    run-tests:
        needs: fix-code-style
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis
                ports:
                    - 6379:6379
                options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
        strategy:
            fail-fast: true
            matrix:
                php: [7.4]
                laravel: [8.*]
                dependency-version: [prefer-stable]
                include:
                    -   laravel: 8.*
                        testbench: 6.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
        continue-on-error: ${{ matrix.allow-failures }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer config --auth http-basic.satis.mailcoach.app ${{ secrets.SATIS_MAILCOACH_APP_USERNAME }} ${{ secrets.SATIS_MAILCOACH_APP_PASSWORD }}
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
            -   name: Execute tests
                run: vendor/bin/phpunit
                env:
                    REDIS_PORT: ${{ job.services.redis.ports[6379] }}
